version: '3.7'

services:
  web:
    build: .
    command: gunicorn app:app --config gunicorn.config.py
    expose:
      - 5000
  nginx:
    build: ./nginx
#    volumes:
#      - static_volume:/home/app/web/project/static
    ports:
      - 80:80
    depends_on:
      - web